# Form implementation generated from reading ui file '/Users/egorttimofeev/vs_code_projects/curs_project/uic/Main_window_user.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(657, 404)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(510, 10, 141, 32))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 53, 271, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.task_time = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.task_time.setGeometry(QtCore.QRect(20, 160, 291, 24))
        self.task_time.setObjectName("task_time")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 200, 113, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 10, 121, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 200, 16))
        self.label_3.setObjectName("label_3")
        self.radioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(20, 240, 141, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 270, 141, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 320, 200, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 350, 200, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 380, 200, 16))
        self.label_6.setObjectName("label_6")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(300, 50, 341, 300))
        self.listWidget.setObjectName("listWidget")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 40, 141, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton_3.clicked.connect(self.add_activity)

        self.total_time = 0
        self.busy_time = 0
        self.free_time = 0

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Main_window"))
        self.pushButton.setText(_translate("MainWindow", "Личный кабинет"))
        self.pushButton_3.setText(_translate("MainWindow", "Добавить"))
        self.label.setText(_translate("MainWindow", "Добавить занятие:"))
        self.label_2.setText(_translate("MainWindow", "Занятие"))
        self.label_3.setText(_translate("MainWindow", "Выполнение занятия (мин.)"))
        self.radioButton.setText(_translate("MainWindow", "Занятое время"))
        self.radioButton_2.setText(_translate("MainWindow", "Свободное время"))
        self.label_4.setText(_translate("MainWindow", "Время на работу:"))
        self.label_5.setText(_translate("MainWindow", "Время на отдых:"))
        self.label_6.setText(_translate("MainWindow", "Общее время:"))
        self.pushButton_2.setText(_translate("MainWindow", "По месяцам"))

    def add_activity(self):
        activity = self.lineEdit.text()
        duration = self.task_time.value()
        is_busy = self.radioButton.isChecked()

        if activity and duration:
            self.listWidget.addItem(f"{activity} - {duration} мин. {'(Занятое время)' if is_busy else '(Свободное время)'}")
            self.update_times(duration, is_busy)

    def update_times(self, duration, is_busy):
        self.total_time += duration
        if is_busy:
            self.busy_time += duration
        else:
            self.free_time += duration

        self.label_4.setText(f"Время на работу: {self.busy_time} мин.")
        self.label_5.setText(f"Время на отдых: {self.free_time} мин.")
        self.label_6.setText(f"Общее время: {self.total_time} мин.")